name: deployment

on:
  release:
    types: [ published ]

jobs:
  production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Restore cached vendor files
        id: cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: vendor-${{ hashFiles('**/composer.lock') }}-${{ secrets.CACHE_VERSION }}
      - name: Fail without cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1
      - name: Connect to server
      - name: Rsync changes
      - name: Migrate database
        run: php artisan migrate
